# 5. Multivariate Distribution

### Imports

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Covariance

- Covariance breaks the square term in the variance
- (x - u)^2
- and replaces it with each term
- (x1 - u1)(x2 - u2)

Variance always positive but Covariance can be negative

### Load Data

In [5]:
data = pd.read_csv('data/height_weight multi_d.csv')[['height', 'weight']]

In [6]:
data.head()

height  weight
0   71.74  259.88
1   71.00  186.73
2   63.83  172.17
3   67.74  174.66
4   67.28  169.20

### Numpy Covariance

In [16]:
covariance = np.cov(data)

In [17]:
covariance

array([[17698.3298 , 10886.7211 , 10191.5438 , ...,  9768.2288 ,
         6992.2231 ,  4852.1306 ],
       [10886.7211 ,  6696.71645,  6269.0941 , ...,  6008.7016 ,
         4301.10545,  2984.6767 ],
       [10191.5438 ,  6269.0941 ,  5868.7778 , ...,  5625.0128 ,
         4026.4561 ,  2794.0886 ],
       ...,
       [ 9768.2288 ,  6008.7016 ,  5625.0128 , ...,  5391.3728 ,
         3859.2136 ,  2678.0336 ],
       [ 6992.2231 ,  4301.10545,  4026.4561 , ...,  3859.2136 ,
         2762.47445,  1916.9707 ],
       [ 4852.1306 ,  2984.6767 ,  2794.0886 , ...,  2678.0336 ,
         1916.9707 ,  1330.2482 ]])

### Hmmm that is odd
Issue is that `np.cov` expects each column to be an observations and each row to be a variable
- Transpose dataset
- Or set `rowvar=False`

In [18]:
covariance = np.cov(data, rowvar=False)

In [19]:
covariance

array([[  18.60200779,   78.50218098],
       [  78.50218098, 1512.91208783]])

### Pandas Covariance

In [20]:
covariance = data.cov()

In [21]:
covariance

height       weight
height  18.602008    78.502181
weight  78.502181  1512.912088

But this has both the **correlation** between columns and the **variance**
- To get just correlation we need the correlation matrix
- Do this by dividing by each element by the product of the std.dev of each variable in each element
- Diagonal terms reduce to 1, off-diagonal columns are the correlation between columns

Correlation_a_b = (Cov_a_b) / (st_dev_a * st_dev_b)

### Numpy Correlation

In [26]:
corr = np.corrcoef(data.T)

In [27]:
corr

array([[1.        , 0.46794517],
       [0.46794517, 1.        ]])

### Pandas Correlation

In [29]:
corr = data.corr()

In [31]:
corr

height    weight
height  1.000000  0.467945
weight  0.467945  1.000000